### PR TITLE
support atomic upsert.

### PR DESCRIPTION
**Pull request by kunchenguid**
azure has implemented support for atomic upsert. this pull request is to provide support through DoQmentDB.

### CODE REVIEW

**Comment by a8m** [comment]
This is great @kunchenguid 
Thank you.

**Comment by kunchenguid** [comment]
glad to help. this is a great project! so much better than the native azure sdk. :)

**Comment by a8m** [comment]
haha thanks buddy.
by the way, I added you as a collaborator :shipit:

**Comment by kunchenguid** [comment]
thanks man! cheers

**Pull request merged**
